### ISSUE TITLE
TypeError: 'numpy.float64' object does not support item assignment

### ISSUE THREAD

**Issue by tillea** [ryansmcgee/seirsplus#65]
Hi,
in Debian we run some CI test which is triggered like this:

     python3 test_model.py

(where [test_model.py code can be downloaded here](https://salsa.debian.org/med-team/seirsplus/-/blob/master/debian/tests/test_model.py?ref_type=heads).  This leads to

    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.d39z3x5o/downtmp/autopkgtest_tmp/test_model.py", line 20, in <module>
        model.run(T=300, checkpoints=checkpoints)
      File "/usr/lib/python3/dist-packages/seirsplus/models.py", line 1366, in run
        running = self.run_iteration()
                  ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3/dist-packages/seirsplus/models.py", line 1248, in run_iteration
        self.timer_state[transitionNode] = 0.0
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
    TypeError: 'numpy.float64' object does not support item assignment

You can find the [full build log](https://salsa.debian.org/med-team/seirsplus/-/jobs/6737292#L686) in Debian CI.  The version fo seirsplus is the tag 1.1.0.

Kind regards, Andreas.

**Comment by tillea** [comment]
You might like to evaluate [this patch](https://salsa.debian.org/med-team/seirsplus/-/blob/master/debian/patches/numpy-2.4.patch?ref_type=heads)
